"""
gen_sql.py - generates sql/ from data/products.json. Deterministic.

    python tools/gen_sql.py
"""

import json
from pathlib import Path
from argparse import ArgumentParser

# Helpers

_BIDI_MARKS = '\u200e\u200f\u202a\u202b\u202c\u202d\u202e'
_BIDI_TABLE = str.maketrans('', '', _BIDI_MARKS)

def sql_text(s: str) -> str:
    return s.translate(_BIDI_TABLE).replace("'", "''")

def sql_str(s: str | None) -> str:
    if s is None:
        return "NULL"
    return f"'{sql_text(s)}'"

def sql_date(s: str | None) -> str:
    if s is None:
        return "NULL"
    return f"'{s}'"

def write_utf8(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    print(f"  {path.name:<34} {path.stat().st_size:>9,} bytes")

# Schema: (name, mysql_type, pg_type, mssql_type, renderer)

COLUMNS = [
    ("id",       "INT",           "INT",         "INT",         lambda r: str(r["id"])),
    ("registration_number", "VARCHAR(50)",   "VARCHAR(50)",   "NVARCHAR(50)",   lambda r: sql_str(r["registration_number"])),
    ("code",     "VARCHAR(20)",   "VARCHAR(20)",   "NVARCHAR(20)",   lambda r: sql_str(r["code"])),
    ("international_common_name", "VARCHAR(200)", "VARCHAR(200)", "NVARCHAR(200)", lambda r: sql_str(r["international_common_name"])),
    ("brand_name", "VARCHAR(200)", "VARCHAR(200)", "NVARCHAR(200)", lambda r: sql_str(r["brand_name"])),
    ("form",     "VARCHAR(100)",  "VARCHAR(100)",  "NVARCHAR(100)",  lambda r: sql_str(r["form"])),
    ("dosage",   "VARCHAR(50)",   "VARCHAR(50)",   "NVARCHAR(50)",   lambda r: sql_str(r["dosage"])),
    ("packaging","VARCHAR(50)",   "VARCHAR(50)",   "NVARCHAR(50)",   lambda r: sql_str(r["packaging"])),
    ("list",     "VARCHAR(20)",   "VARCHAR(20)",   "NVARCHAR(20)",   lambda r: sql_str(r["list"])),
    ("p1",       "VARCHAR(20)",   "VARCHAR(20)",   "NVARCHAR(20)",   lambda r: sql_str(r["p1"])),
    ("p2",       "VARCHAR(20)",   "VARCHAR(20)",   "NVARCHAR(20)",   lambda r: sql_str(r["p2"])),
    ("obs",      "VARCHAR(500)",  "VARCHAR(500)",  "NVARCHAR(500)",  lambda r: sql_str(r["obs"])),
    ("laboratories_holding_the_registration_decision", "VARCHAR(300)", "VARCHAR(300)", "NVARCHAR(300)", lambda r: sql_str(r["laboratories_holding_the_registration_decision"])),
    ("country_of_the_laboratory_holding_the_registration_decision", "VARCHAR(100)", "VARCHAR(100)", "NVARCHAR(100)", lambda r: sql_str(r["country_of_the_laboratory_holding_the_registration_decision"])),
    ("initial_registration_date", "DATE", "DATE", "DATE", lambda r: sql_date(r["initial_registration_date"])),
    ("final_registration_date",   "DATE", "DATE", "DATE", lambda r: sql_date(r["final_registration_date"])),
    ("type",     "VARCHAR(20)",   "VARCHAR(20)",   "NVARCHAR(20)",   lambda r: sql_str(r["type"])),
    ("status",   "VARCHAR(20)",   "VARCHAR(20)",   "NVARCHAR(20)",   lambda r: sql_str(r["status"])),
    ("shelf_life","VARCHAR(20)",  "VARCHAR(20)",   "NVARCHAR(20)",   lambda r: sql_str(r["shelf_life"])),
]

TABLE = "products"
BATCH_SIZE = 500

_RESERVED = {"list", "type"}

def q(name: str, dialect: str) -> str:
    if name not in _RESERVED:
        return name
    if dialect == "mysql":
        return f"`{name}`"
    if dialect == "postgres":
        return f'"{name}"'
    return f"[{name}]"


# Dialects

DIALECTS = [
    {"file": "mysql.sql",     "dialect": "mysql",     "type_idx": 1, "drop": "DROP TABLE IF EXISTS products;"},
    {"file": "postgres.sql",  "dialect": "postgres",  "type_idx": 2, "drop": "DROP TABLE IF EXISTS products;"},
    {"file": "sqlserver.sql", "dialect": "sqlserver", "type_idx": 3, "drop": "IF OBJECT_ID('products') IS NOT NULL DROP TABLE products;"},
]

# Main

def main() -> None:
    parser = ArgumentParser()
    parser.add_argument(
        "--out-dir",
        default=str(Path(__file__).resolve().parent.parent),
    )
    args = parser.parse_args()
    out_dir = Path(args.out_dir)

    # Load
    print("\nLoading")
    products = json.loads(
        (out_dir / "data" / "products.json").read_text(encoding="utf-8")
    )
    print(f"  {len(products)} products")

    # SQL
    print("\nsql/")
    for d in DIALECTS:
        ti = d["type_idx"]
        dialect = d["dialect"]
        lines: list[str] = []

        lines.append("-- Algeria: National Nomenclature of Pharmaceutical Products.")
        lines.append("-- Generated by tools/gen_sql.py - do not edit by hand.")
        lines.append("-- Source: MIPH - https://www.miph.gov.dz/fr/nomenclature-nationale-des-produits-pharmaceutiques")
        lines.append("")
        lines.append(d["drop"])
        lines.append("")

        # CREATE TABLE
        lines.append(f"CREATE TABLE {TABLE} (")
        for i, col in enumerate(COLUMNS):
            col_type = col[ti]
            quoted = q(col[0], dialect)
            comma = "," if i < len(COLUMNS) - 1 else ""
            if col[0] == "id":
                lines.append(f"    {quoted:<55} {col_type} PRIMARY KEY{comma}")
            else:
                lines.append(f"    {quoted:<55} {col_type}{comma}")
        lines.append(");")
        lines.append("")

        # INSERT in batches
        col_list = ", ".join(q(c[0], dialect) for c in COLUMNS)
        for i in range(0, len(products), BATCH_SIZE):
            batch = products[i : i + BATCH_SIZE]
            lines.append(f"INSERT INTO {TABLE} ({col_list}) VALUES")
            rows = [
                f"    ({', '.join(col[4](p) for col in COLUMNS)})"
                for p in batch
            ]
            lines.append(",\r\n".join(rows) + ";")
            lines.append("")

        write_utf8(out_dir / "sql" / d["file"], "\r\n".join(lines) + "\r\n")

    print(f"\nBuild OK: {len(products)} products.\n")

if __name__ == "__main__":
    main()
